# -*- coding: utf-8 -*-
"""Text_to_Img.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sqtfogl1We9zXANZjWu-tDlbbPUGZ8En
"""

!pip install --upgrade diffusers transformers scipy
!pip install accelerate
from PIL import Image
import io
import IPython.display as display
import torch
import accelerate
from torch import autocast
from diffusers import StableDiffusionPipeline

prompt = input("Please Input Your Prompt")

modelid = "CompVis/stable-diffusion-v1-4"
device = "cuda"
pipe = StableDiffusionPipeline.from_pretrained(modelid, revision="fp16", torch_dtype=torch.float16)
pipe.to(device)

def generate():
    with autocast(device):
      generator = torch.Generator("cuda")
      output = pipe(prompt, guidance_scale=8.5)
      image = pipe(prompt, guidance_scale=7.5, generator=generator).images[0]
    image.save('generatedimage.png')
    buffer = io.BytesIO()
    image.save(buffer, format='PNG')
    display.display(display.Image(buffer.getvalue()))

generate()