# Generated by Django 4.2 on 2023-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="platform",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="game",
            name="publisher",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
